## Numpy Array & Basics

In [2]:
import numpy as np

#### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D-Array: ",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D-Array: ", arr_2d)


1D-Array:  [1 2 3 4 5]
2D-Array:  [[1 2 3]
 [4 5 6]]


#### List vs Numpy Array

In [4]:
py_list = [1,2,3]
print("python list multiplication with 2: ", py_list*2)

np_array = np.array([1,2,3])
print("Numpy array multiplication with 2: ", np_array*2)

# operation time
import time

sl = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time: ", time.time()-sl)

sn = time.time()
np_array = np.arange(1000000) * 2
print("Numpy operation time: ", time.time()-sn)

python list multiplication with 2:  [1, 2, 3, 1, 2, 3]
Numpy array multiplication with 2:  [2 4 6]
List operation time:  0.049344778060913086
Numpy operation time:  0.0036773681640625


#### Creating Array from scratch

In [5]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("Ones array: \n", ones)

full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,10,2)
print("Sequence: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.38003773 0.51166203 0.75935924]
 [0.36527595 0.81913554 0.25690085]]
Sequence: 
 [0 2 4 6 8]


#### Vector, matrix and tensor

In [6]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
                   [5,6,8]])
print("Matrix: \n", matrix)

tensor = np.array([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [5 6 8]]
Tensor: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Array Properties

In [7]:
arr = np.array([[1,2,0.3],
                [4,5,6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  float64


#### Array Reshaping

In [10]:
arr = np.arange(12)
print("Original array: \n",arr)

arr_reshaped = arr.reshape((3,4))
print("Reshaped array:\n", arr_reshaped)

flattened = arr_reshaped.flatten()
print("Flattened array: \n", flattened)

raveled = arr_reshaped.ravel()
print("Ravelled array: \n", raveled)

# flatten() creates a copy of the array.
# ravel() returns a view whenever possible (otherwise a copy).

transpose = arr_reshaped.T
print("Transposed array: \n", transpose)

Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
