## Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative indexing:  8


In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[1])
print("Entire coloumn: ", arr_2d[:,1])

Specific element:  6
Entire row:  [4 5 6]
Entire coloumn:  [2 5 8]


#### Sorting

In [12]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array: ", np.sort(unsorted))

unsorted_2d_array = np.array([[3,1], [1,2], [2,3]])

print("Sorted 2d array by column: ", np.sort(unsorted_2d_array, axis=0))

print("Sorted 2d array by row: ", np.sort(unsorted_2d_array, axis=1))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted 2d array by column:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by row:  [[1 3]
 [1 2]
 [2 3]]


#### Filter

In [15]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)


Even numbers:  [ 2  4  6  8 10]


#### Filter by mask

In [17]:
mask = numbers>5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


#### Fancy indexing Vs np.where()

In [21]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)

print("NP where: ", numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


#### Condition Arrays

In [23]:
condition_array = np.where(numbers>5, numbers*4, numbers)
print(condition_array)


[ 1  2  3  4  5 24 28 32 36 40]


#### Adding and Removing data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

addition = arr1 + arr2
print("Addition: ", addition)

concatenation = np.concatenate((arr1, arr2))
print("Concatenation: ", concatenation)

Addition:  [5 7 9]


TypeError: only integer scalar arrays can be converted to a scalar index